source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.0'
inhibit_all_warnings!

xcodeproj 'GeoIp'

pod 'ObjectiveSugar', '~> 0.5'

target :GeoIpTests do
  pod 'OCMock', '~> 2.0.1'
pod 'Kiwi', '~> 2.4.0'
end

